/* soapChinaStockWebServiceSoapProxy.h
   Generated by gSOAP 2.8.14 from stock.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapChinaStockWebServiceSoapProxy_H
#define soapChinaStockWebServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC ChinaStockWebServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'ChinaStockWebServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ChinaStockWebServiceSoapProxy();
	/// Construct from another engine state
	ChinaStockWebServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	ChinaStockWebServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	ChinaStockWebServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ChinaStockWebServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ChinaStockWebServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ChinaStockWebServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void ChinaStockWebServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'getStockImageByCode' (returns error code or SOAP_OK)
	virtual	int getStockImageByCode(_ns1__getStockImageByCode *ns1__getStockImageByCode, _ns1__getStockImageByCodeResponse *ns1__getStockImageByCodeResponse) { return this->getStockImageByCode(NULL, NULL, ns1__getStockImageByCode, ns1__getStockImageByCodeResponse); }
	virtual	int getStockImageByCode(const char *endpoint, const char *soap_action, _ns1__getStockImageByCode *ns1__getStockImageByCode, _ns1__getStockImageByCodeResponse *ns1__getStockImageByCodeResponse);

	/// Web service operation 'getStockImageByteByCode' (returns error code or SOAP_OK)
	virtual	int getStockImageByteByCode(_ns1__getStockImageByteByCode *ns1__getStockImageByteByCode, _ns1__getStockImageByteByCodeResponse *ns1__getStockImageByteByCodeResponse) { return this->getStockImageByteByCode(NULL, NULL, ns1__getStockImageByteByCode, ns1__getStockImageByteByCodeResponse); }
	virtual	int getStockImageByteByCode(const char *endpoint, const char *soap_action, _ns1__getStockImageByteByCode *ns1__getStockImageByteByCode, _ns1__getStockImageByteByCodeResponse *ns1__getStockImageByteByCodeResponse);

	/// Web service operation 'getStockImage_kByCode' (returns error code or SOAP_OK)
	virtual	int getStockImage_USCOREkByCode(_ns1__getStockImage_USCOREkByCode *ns1__getStockImage_USCOREkByCode, _ns1__getStockImage_USCOREkByCodeResponse *ns1__getStockImage_USCOREkByCodeResponse) { return this->getStockImage_USCOREkByCode(NULL, NULL, ns1__getStockImage_USCOREkByCode, ns1__getStockImage_USCOREkByCodeResponse); }
	virtual	int getStockImage_USCOREkByCode(const char *endpoint, const char *soap_action, _ns1__getStockImage_USCOREkByCode *ns1__getStockImage_USCOREkByCode, _ns1__getStockImage_USCOREkByCodeResponse *ns1__getStockImage_USCOREkByCodeResponse);

	/// Web service operation 'getStockImage_kByteByCode' (returns error code or SOAP_OK)
	virtual	int getStockImage_USCOREkByteByCode(_ns1__getStockImage_USCOREkByteByCode *ns1__getStockImage_USCOREkByteByCode, _ns1__getStockImage_USCOREkByteByCodeResponse *ns1__getStockImage_USCOREkByteByCodeResponse) { return this->getStockImage_USCOREkByteByCode(NULL, NULL, ns1__getStockImage_USCOREkByteByCode, ns1__getStockImage_USCOREkByteByCodeResponse); }
	virtual	int getStockImage_USCOREkByteByCode(const char *endpoint, const char *soap_action, _ns1__getStockImage_USCOREkByteByCode *ns1__getStockImage_USCOREkByteByCode, _ns1__getStockImage_USCOREkByteByCodeResponse *ns1__getStockImage_USCOREkByteByCodeResponse);

	/// Web service operation 'getStockInfoByCode' (returns error code or SOAP_OK)
	virtual	int getStockInfoByCode(_ns1__getStockInfoByCode *ns1__getStockInfoByCode, _ns1__getStockInfoByCodeResponse *ns1__getStockInfoByCodeResponse) { return this->getStockInfoByCode(NULL, NULL, ns1__getStockInfoByCode, ns1__getStockInfoByCodeResponse); }
	virtual	int getStockInfoByCode(const char *endpoint, const char *soap_action, _ns1__getStockInfoByCode *ns1__getStockInfoByCode, _ns1__getStockInfoByCodeResponse *ns1__getStockInfoByCodeResponse);

	/// Web service operation 'getStockImageByCode' (returns error code or SOAP_OK)
	virtual	int getStockImageByCode_(_ns1__getStockImageByCode *ns1__getStockImageByCode, _ns1__getStockImageByCodeResponse *ns1__getStockImageByCodeResponse) { return this->getStockImageByCode_(NULL, NULL, ns1__getStockImageByCode, ns1__getStockImageByCodeResponse); }
	virtual	int getStockImageByCode_(const char *endpoint, const char *soap_action, _ns1__getStockImageByCode *ns1__getStockImageByCode, _ns1__getStockImageByCodeResponse *ns1__getStockImageByCodeResponse);

	/// Web service operation 'getStockImageByteByCode' (returns error code or SOAP_OK)
	virtual	int getStockImageByteByCode_(_ns1__getStockImageByteByCode *ns1__getStockImageByteByCode, _ns1__getStockImageByteByCodeResponse *ns1__getStockImageByteByCodeResponse) { return this->getStockImageByteByCode_(NULL, NULL, ns1__getStockImageByteByCode, ns1__getStockImageByteByCodeResponse); }
	virtual	int getStockImageByteByCode_(const char *endpoint, const char *soap_action, _ns1__getStockImageByteByCode *ns1__getStockImageByteByCode, _ns1__getStockImageByteByCodeResponse *ns1__getStockImageByteByCodeResponse);

	/// Web service operation 'getStockImage_kByCode' (returns error code or SOAP_OK)
	virtual	int getStockImage_USCOREkByCode_(_ns1__getStockImage_USCOREkByCode *ns1__getStockImage_USCOREkByCode, _ns1__getStockImage_USCOREkByCodeResponse *ns1__getStockImage_USCOREkByCodeResponse) { return this->getStockImage_USCOREkByCode_(NULL, NULL, ns1__getStockImage_USCOREkByCode, ns1__getStockImage_USCOREkByCodeResponse); }
	virtual	int getStockImage_USCOREkByCode_(const char *endpoint, const char *soap_action, _ns1__getStockImage_USCOREkByCode *ns1__getStockImage_USCOREkByCode, _ns1__getStockImage_USCOREkByCodeResponse *ns1__getStockImage_USCOREkByCodeResponse);

	/// Web service operation 'getStockImage_kByteByCode' (returns error code or SOAP_OK)
	virtual	int getStockImage_USCOREkByteByCode_(_ns1__getStockImage_USCOREkByteByCode *ns1__getStockImage_USCOREkByteByCode, _ns1__getStockImage_USCOREkByteByCodeResponse *ns1__getStockImage_USCOREkByteByCodeResponse) { return this->getStockImage_USCOREkByteByCode_(NULL, NULL, ns1__getStockImage_USCOREkByteByCode, ns1__getStockImage_USCOREkByteByCodeResponse); }
	virtual	int getStockImage_USCOREkByteByCode_(const char *endpoint, const char *soap_action, _ns1__getStockImage_USCOREkByteByCode *ns1__getStockImage_USCOREkByteByCode, _ns1__getStockImage_USCOREkByteByCodeResponse *ns1__getStockImage_USCOREkByteByCodeResponse);

	/// Web service operation 'getStockInfoByCode' (returns error code or SOAP_OK)
	virtual	int getStockInfoByCode_(_ns1__getStockInfoByCode *ns1__getStockInfoByCode, _ns1__getStockInfoByCodeResponse *ns1__getStockInfoByCodeResponse) { return this->getStockInfoByCode_(NULL, NULL, ns1__getStockInfoByCode, ns1__getStockInfoByCodeResponse); }
	virtual	int getStockInfoByCode_(const char *endpoint, const char *soap_action, _ns1__getStockInfoByCode *ns1__getStockInfoByCode, _ns1__getStockInfoByCodeResponse *ns1__getStockInfoByCodeResponse);
};
#endif
